docs: improved cloudflare docs
ZephyrCloudIO/zephyr-documentation pull request #33
Opened 2024-11-01 02:08 UTC by arthurfiorette

### What's added in this PR?

[_Provide an implementation summary. What did you add beyond the described task? What are the additional details you'd like people to pay attention to? To help people review this PR understand what's changed._]

### What's the issues or discussion related to this PR (optional) ?

[_Provide some background information related to this PR, including issues or task. Prior to this PR what's the behavior that wasn't expected._]

[_If there wasn't discussion related to this PR, you can include the reasoning behind this PR of why you did it._]

### Feature related update for this PR (if applicable)?

### (Optional) What's left to be done for this PR?

### Who do you wish to review this PR other than required reviewers?

d
### (Required) Pre-PR/Merge checklist

- [ ] I have added/updated our feature to sync with this PR
- [ ] I have added an explanation of my changes
- [ ] I have/will run tests, or ask for help to add test

2024-11-01 09:07 UTC, StashBank commented
Sugest have screenshots in dark mode as we have our UI in that mode

2024-11-11 14:03 UTC, zmzlois approved these changes

2024-11-12 12:20 UTC, zmzlois commented on docs/cloud/cloudflare.mdx
> +![dns](../public/cf-dns-entry-cname.png)
give them a table they can copy paste?

2024-11-12 12:23 UTC, zmzlois commented on docs/cloud/cloudflare.mdx
> +  project](https://developers.cloudflare.com/pages).
```suggestion
  project](https://developers.cloudflare.com/pages). This field will become the name of your Cloudflare Pages project.
```

2024-11-12 12:24 UTC, zmzlois commented on docs/cloud/cloudflare.mdx
> +  new one is set.
new one is vaguely implying "just an integration" or "default integration" and it needs to be default integration to be effective

2024-11-12 12:27 UTC, zmzlois requested changes
in general very well written ❤️

2024-11-12 13:18 UTC, zmzlois approved these changes
LGTM

2024-11-12 13:18 UTC, merged