feat: zephyr dependencies section
ZephyrCloudIO/zephyr-documentation pull request #47
Opened 2024-12-20 13:17 UTC by StashBank

### What's added in this PR?

[_Provide an implementation summary. What did you add beyond the described task? What are the additional details you'd like people to pay attention to? To help people review this PR understand what's changed._]

### What's the issues or discussion related to this PR (optional) ?

[_Provide some background information related to this PR, including issues or task. Prior to this PR what's the behavior that wasn't expected._]

[_If there wasn't discussion related to this PR, you can include the reasoning behind this PR of why you did it._]

### Feature related update for this PR (if applicable)?

### (Optional) What's left to be done for this PR?

### Who do you wish to review this PR other than required reviewers?

### (Required) Pre-PR/Merge checklist

- [ ] I have added/updated our feature to sync with this PR
- [ ] I have added an explanation of my changes
- [ ] I have/will run tests, or ask for help to add test

2024-12-20 14:51 UTC, StashBank commented
> Need to add description at these places:
> 
> * https://docs.zephyr-cloud.io/general/why-zephyr-cloud
> * https://docs.zephyr-cloud.io/how-to/mf-guide
> 
> Is it a hard requirement? Is it ok to skip? If they skip what happens? In what scenario does it work better?

Updated. 

not hard requirements.
ok to skip.
if skip will be uses latest version of remote.
I don't know scenario for better usage.

2024-12-20 16:15 UTC, valorkin approved these changes

2024-12-23 13:25 UTC, arthurfiorette requested changes

2024-12-23 13:25 UTC, arthurfiorette commented on docs/general/create-mf-app.mdx
> +For example we have [react-tractor-sample](https://github.com/ZephyrCloudIO/zephyr-examples/tree/main/examples/react-tractor-sample).
Chat GPT is very good to rewrite text into one more suitable for docs :)

https://chatgpt.com/share/6769629a-7764-8001-a9b7-f887fa31d6a4

---

For example, consider the [react-tractor-sample](https://github.com/ZephyrCloudIO/zephyr-examples/tree/main/examples/react-tractor-sample) repository. It includes an application called `team-red`, which depends on two other applications: `team-green` and `team-blue`.

To specify the version of each dependency, you can define `zephyrDependencies` in the `package.json` file like this:

```json title=package.json
{
  "name": "team-red",
  "version": "0.1.0",
  "scripts": {
    "build": "nx run team-red:build --skip-nx-cache"
  },
  "private": true,
  "zephyrDependencies": {
    "team-blue": "0.1.0",
    "team-green": "0.1.0"
  }
}
```

If you omit the `zephyrDependencies` configuration, the latest versions of the remote applications will be used by default.

2024-12-23 13:34 UTC, zmzlois commented on docs/how-to/mf-guide.mdx
> +```json title="Optional Zephyr Dependencies in host package.json"
```suggestion
Optionally, to specify which version of the remote application host app should be using, you can add a field in host's `package.json`. If the remote's version is not specified in the host app, the latest version will always be used. 
```json title="host package.json"
```

2024-12-27 15:02 UTC, arthurfiorette approved these changes

2024-12-27 15:12 UTC, zmzlois approved these changes

2024-12-27 15:12 UTC, merged